# Generated by Django 4.1.6 on 2023-02-13 20:05

from django.db import migrations


class Migration(migrations.Migration):

    def load_initial_data(apps, schema_editor):
        user_model = apps.get_model('api', 'User')
        user_model.objects.create (username="admin", password="Senai@2023")

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(load_initial_data),
    ]
